# <en><center>Dataset Basics</center></en>

## Table of Contents

- [Loading Datasets](#Loading-Datasets)
- [Numpy vs Pandas](#Numpy-vs-Pandas)

## Library

In [1]:
import numpy as np
import pandas as pd
import pickle

## Loading Datasets

### Dataset

In [2]:
heart_file = "C:\\Users\\pyria\\OneDrive\\Documents\\Personal Development\\Python\\Bootcamps\\\
Pandas Bootcamp\\P87-Section-2-Dataset-Basics-Resources\\heart.csv"

#### The best method - pandas read_csv

In [4]:
df = pd.read_csv(heart_file)
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### Numpy loadtext and genfromtxt

- It fails without extra arguments
- It is not as smart and we have to tell it what to do.
- It is designed for loading in data saved using np.savetxt.
- It was never meant to be used as a robust data loader.

In [6]:
data = np.loadtxt(heart_file, delimiter = ",", skiprows = 1)
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [5]:
data = np.genfromtxt(heart_file, delimiter = ",", dtype = None, names = True, encoding = "utf-8-sig")
print(data)
print(data.dtype)

[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 3, 150, 283, 1, 0, 162, 0, 1. , 2, 0, 2, 1)
 (50, 0, 2, 120, 219, 0, 1, 158, 0, 1.6, 1, 0, 2, 1)
 (58, 0, 2, 120, 340, 0, 1, 172, 0, 0. , 2, 0, 2, 1)
 (66, 0, 3, 150, 226, 0, 1, 114, 0, 2.6, 0, 0, 2, 1)
 (43, 1, 0, 150, 247, 0, 1, 171, 0, 1.5, 2, 0,

### Manual Loading
- Gives weird file structures

In [8]:
def load_file(filename):
    with open(heart_file, encoding = "utf-8-sig") as f:
        data, cols = [], []
        for i, line in enumerate(f.read().splitlines()):
            if i == 0:
                cols += line.split(",")
            else:
                data.append([float(x) for x in line.split(",")])
        df = pd.DataFrame(data, columns = cols)
    return df
load_file(heart_file).head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0    0.0      0.8   
4  57.0  0.0  0.0     120.0  354.0  0.0      1.0    163.0    1.0      0.6   

   slope   ca  thal  target  
0    0.0  0.0   1.0     1.0  
1    0.0  0.0   2.0     1.0  
2    2.0  0.0   2.0     1.0  
3    2.0  0.0   2.0     1.0  
4    2.0  0.0   2.0     1.0

### Pickles!

In [9]:
pickle_file = "C:\\Users\\pyria\\OneDrive\\Documents\\Personal Development\\Python\\Bootcamps\\Pandas Bootcamp\\\
P87-Section-2-Dataset-Basics-Resources\\heart.pkl"

df = pd.read_pickle(pickle_file)
df.head

<bound method NDFrame.head of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1      

### Loading Data Summary

- Use Pandas pd.read_csv 99% of the time.
- Use pd.read_* for other cases(pd.read_excel, pd.read_pickle, etc)
- If pd can't handle it, numpy probably can't.
- If you use a manual function, save your data to a sensible format.

## Numpy vs Pandas

1. Pandas has a numpy core.
2. Extra structure and tools, but sometimes you have to strip it away.

In [10]:
df = pd.read_csv(heart_file)

In [11]:
data = df.to_numpy()
data = df.values
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [12]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [13]:
print(data.dtype, data)

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [15]:
data[0,0] = 100
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [17]:
df2 = df[["age", "sex", "cp"]]
data2 = df2.to_numpy().copy() # you need to get a copy of the array
data2[0,0]= 100
df2

age  sex  cp
0    100    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [18]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [20]:
print(df["age"].quantile(0.5))

55.0


In [21]:
print(df["age"].to_numpy().reshape((3,-1)))

[[63 37 41 56 57 57 56 44 52 57 54 48 49 64 58 50 58 66 43 69 59 44 42 61
  40 71 59 51 65 53 41 65 44 54 51 46 54 54 65 65 51 48 45 53 39 52 44 47
  53 53 51 66 62 44 63 52 48 45 34 57 71 54 52 41 58 35 51 45 44 62 54 51
  29 51 43 55 51 59 52 58 41 45 60 52 42 67 68 46 54 58 48 57 52 54 45 53
  62 52 43 53 42]
 [59 63 42 50 68 69 45 50 50 64 57 64 43 55 37 41 56 46 46 64 59 41 54 39
  34 47 67 52 74 54 49 42 41 41 49 60 62 57 64 51 43 42 67 76 70 44 60 44
  42 66 71 64 66 39 58 47 35 58 56 56 55 41 38 38 67 67 62 63 53 56 48 58
  58 60 40 60 64 43 57 55 65 61 58 50 44 60 54 50 41 51 58 54 60 60 59 46
  67 62 65 44 60]
 [58 68 62 52 59 60 49 59 57 61 39 61 56 43 62 63 65 48 63 55 65 56 54 70
  62 35 59 64 47 57 55 64 70 51 58 60 77 35 70 59 64 57 56 48 56 66 54 69
  51 43 62 67 59 45 58 50 62 38 66 52 53 63 54 66 55 49 54 56 46 61 67 58
  47 52 58 57 58 61 42 52 59 40 61 46 59 57 57 55 61 58 58 67 44 63 63 59
  57 45 68 57 57]]


Most of the time, better to keep things in DataFrame format, as you can do more.

## Creating DataFrames

In [25]:
data = np.random.random(size = (5,3))
print(data)
df = pd.DataFrame(data = data, columns = ["A", "B","C"])
df

[[0.25219688 0.5293432  0.45144641]
 [0.56515903 0.71756664 0.21117433]
 [0.03329659 0.34016218 0.68356936]
 [0.3091201  0.94986377 0.49021003]
 [0.1056806  0.3951101  0.72983312]]


A         B         C
0  0.252197  0.529343  0.451446
1  0.565159  0.717567  0.211174
2  0.033297  0.340162  0.683569
3  0.309120  0.949864  0.490210
4  0.105681  0.395110  0.729833

Create a DataFrame with a dictionary

In [26]:
df = pd.DataFrame({"A": [1,2,3], "B": ["Sam","Alex","John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [30]:
data = [{"A": 1, "B": "Sam"},{"A": 2, "B": "Alex"}, {"A":3, "B":"John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

Create a DataFrame with a numpy structure

In [28]:
dtype = [("A", np.int),("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3,"John")], dtype = dtype)
df = pd.DataFrame(data)
df

C:\Users\pyria\AppData\Local\Temp\ipykernel_6440\2588207264.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int),("B", (np.str, 20))]
C:\Users\pyria\AppData\Local\Temp\ipykernel_6440\2588207264.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/rele

A     B
0  1   Sam
1  2  Alex
2  3  John

## Saving and Serializing a DataFrame

In [36]:
df = pd.DataFrame(np.random.random(size = (100000, 4)), columns = ["A", "B","C","D"])
df.head()

A         B         C         D
0  0.801048  0.328091  0.386883  0.185116
1  0.279739  0.684165  0.180335  0.645072
2  0.646320  0.390665  0.639835  0.729768
3  0.097497  0.735112  0.411006  0.903781
4  0.624882  0.666971  0.509083  0.173215

In [ ]:
df.to_csv("save.csv", index = False, float_format = "%0,4f")

In [ ]:
df.to_pickle("save.pkl")

In [ ]:
df.to_hdf("save.hdf", key = "data", format = "table")

In [ ]:
df.to_feather("save.fth")

## Inspecting Data

In [37]:
dataset = "C:\\Users\\pyria\\OneDrive\\Documents\\Personal Development\\\
Portfolio Projects\\Data Sets\\Astronaut Dataset\\astronauts.csv"

df = pd.read_csv(dataset)

In [38]:
df.head(2)

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0  Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1   Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   

                                          Alma Mater  Undergraduate Major  \
0  University of California-Santa Barbara; Univer...              Geology   
1   Montana State University; University of Colorado  Engineering Physics   

  Graduate Major Military Rank Military Branch  Space Flights  \
0        Geology           NaN             NaN              2   
1  Solar Physics           NaN             NaN              1   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   

                                 Missions Death Date Death Mission  
0  STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                   STS 51-F (Challenger)        NaN           NaN

In [39]:
df.tail()

Name    Year  Group   Status Birth Date  \
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [40]:
df.sample(3)

Name    Year  Group   Status  Birth Date  Birth Place  \
22      Daniel T. Barry  1992.0   14.0  Retired  12/30/1953  Norwalk, CT   
258  James A. Pawelczyk     NaN    NaN  Retired   9/20/1960  Buffalo, NY   
161    David C. Hilmers  1980.0    9.0  Retired   1/28/1950  Clinton, IA   

    Gender                                         Alma Mater  \
22    Male  Cornell University; Princeton University; Univ...   
258   Male  University of Rochester; Pennsylvania State Un...   
161   Male   Cornell University; US Naval Postgraduate School   

        Undergraduate Major  \
22   Electrical Engineering   
258    Biology & Psychology   
161             Mathematics   

                                        Graduate Major Military Rank  \
22   Electrical Engineering; Computer Science; Medi...           NaN   
258                                Physiology; Biology           NaN   
161                             Electrical Engineering       Colonel   

               Military Branch  Space Flights  Space Flight (hr)  Space Walks  \
22                         NaN              3                733            4   
258                        NaN              1                381            0   
161  US Marine Corps (Retired)              4                494            0   

     Space Walks (hr)                                           Missions  \
22               26.0  STS-72 (Endeavor), STS-96 (Discovery), STS-105...   
258               0.0                                  STS-90 (Columbia)   
161               0.0  ST 51-J (Atlantis), STS-26 (Discovery), STS-36...   

    Death Date Death Mission  
22         NaN           NaN  
258        NaN           NaN  
161        NaN           NaN

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 357 non-null    object 
 1   Year                 330 non-null    float64
 2   Group                330 non-null    float64
 3   Status               357 non-null    object 
 4   Birth Date           357 non-null    object 
 5   Birth Place          357 non-null    object 
 6   Gender               357 non-null    object 
 7   Alma Mater           356 non-null    object 
 8   Undergraduate Major  335 non-null    object 
 9   Graduate Major       298 non-null    object 
 10  Military Rank        207 non-null    object 
 11  Military Branch      211 non-null    object 
 12  Space Flights        357 non-null    int64  
 13  Space Flight (hr)    357 non-null    int64  
 14  Space Walks          357 non-null    int64  
 15  Space Walks (hr)     357 non-null    flo

In [43]:
df.describe()

Year       Group  Space Flights  Space Flight (hr)  Space Walks  \
count   330.000000  330.000000     357.000000         357.000000   357.000000   
mean   1985.106061   11.409091       2.364146        1249.266106     1.246499   
std      13.216147    5.149962       1.428700        1896.759857     2.056989   
min    1959.000000    1.000000       0.000000           0.000000     0.000000   
25%    1978.000000    8.000000       1.000000         289.000000     0.000000   
50%    1987.000000   12.000000       2.000000         590.000000     0.000000   
75%    1996.000000   16.000000       3.000000        1045.000000     2.000000   
max    2009.000000   20.000000       7.000000       12818.000000    10.000000   

       Space Walks (hr)  
count        357.000000  
mean           7.707283  
std           13.367973  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           12.000000  
max           67.000000

In [45]:
df.shape

(357, 19)

In [46]:
df.corr()

Year     Group  Space Flights  Space Flight (hr)  \
Year               1.000000  0.980934       0.036420           0.331386   
Group              0.980934  1.000000      -0.011386           0.325683   
Space Flights      0.036420 -0.011386       1.000000           0.325233   
Space Flight (hr)  0.331386  0.325683       0.325233           1.000000   
Space Walks        0.210073  0.217891       0.257073           0.472796   
Space Walks (hr)   0.253502  0.261384       0.258642           0.454408   

                   Space Walks  Space Walks (hr)  
Year                  0.210073          0.253502  
Group                 0.217891          0.261384  
Space Flights         0.257073          0.258642  
Space Flight (hr)     0.472796          0.454408  
Space Walks           1.000000          0.985755  
Space Walks (hr)      0.985755          1.000000

Value_counts only applies to 1 column at a time.

In [ ]:
df["Year"].value_counts()

1978.0    35
1996.0    35
1998.0    25
1990.0    23
1966.0    19
1995.0    19
1980.0    19
1992.0    19
1984.0    18
2000.0    17
1987.0    15
1963.0    14
1985.0    13
2004.0    11
1967.0    11
2009.0     9
1962.0     8
1969.0     7
1959.0     7
1965.0     6
Name: Year, dtype: int64

In [48]:
df.max()

C:\Users\pyria\AppData\Local\Temp\ipykernel_6440\1151452817.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.max()


Name                 Yvonne D. Cagle
Year                          2009.0
Group                           20.0
Status                       Retired
Birth Date                  9/9/1952
Birth Place              Yonkers, NY
Gender                          Male
Space Flights                      7
Space Flight (hr)              12818
Space Walks                       10
Space Walks (hr)                67.0
dtype: object

In [49]:
df["Year"].max()

2009.0

Summary

- Head
- Tail
- Sample
- Info
- Describe